### ISSUE TITLE
Remove AMI logo

### ISSUE THREAD

**Issue by DavidLemayian** [longhotsummer/openbylaws.org.za#13]
Or better still, replace with CfAfrica logo. :)

**Comment by longhotsummer** [comment]
@DavidLemayian can you point me at a CfAfrica logo with a transparent background pls?

**Comment by DavidLemayian** [comment]
[Here](https://drive.google.com/folderview?id=0BxxsGWLSSbD-aDFNUjRsWVRGaEU&usp=sharing) you go. :)

**Comment by DavidLemayian** [comment]
:+1:
